# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Create Plugin Build

on:
  workflow_dispatch:

  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    env:
      RELEASE_PLUGIN_FOLDER: Community.PowerToys.Run.Plugin.JSLHelpers/bin/x64/Release/net9.0-windows10.0.22621.0
      RELEASE_EDITOR_FOLDER: ToolConfigEditor/bin/x64/Release/net9.0-windows10.0.22621.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: |
          dotnet build /p:Platform=x64 -c Release --no-restore

      - name: Copy install script
        shell: pwsh
        run: |
          Copy-Item -Path install_plugin.ps1 -Destination $env:RELEASE_PLUGIN_FOLDER
          Copy-Item -Path install_plugin_link.ps1 -Destination $env:RELEASE_PLUGIN_FOLDER

      - name: Upload plugin build artifact
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v4.4.3
        with:
          # Artifact name
          name: tool-dev-helpers-plugin # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ${{ env.RELEASE_PLUGIN_FOLDER }}/*
          # The desired behavior if no files are found using the provided path.
          retention-days: 3 # optional
          overwrite: true # optional, default is false

      - name: Upload editor build artifact
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v4.4.3
        with:
          # Artifact name
          name: tool-dev-helpers-editor # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ${{ env.RELEASE_EDITOR_FOLDER }}/*
          # The desired behavior if no files are found using the provided path.
          retention-days: 3 # optional
          overwrite: true # optional, default is false

      - name: Create Release ZIP
        if: ${{ github.event_name == 'release' }}
        shell: pwsh
        run: |
          $compressPlugin = @{
            Path = "$env:RELEASE_PLUGIN_FOLDER/*"
            CompressionLevel = "Fastest"
            DestinationPath = "ToolDevHelpers_Plugin_x64.zip"
          }
          Compress-Archive @compressPlugin

          $compressEditor = @{
            Path = "$env:RELEASE_EDITOR_FOLDER/*"
            CompressionLevel = "Fastest"
            DestinationPath = "ToolDevHelpers_Editor_x64.zip"
          }
          Compress-Archive @compressEditor

      - name: Add release asset
        if: ${{ github.event_name == 'release' }}
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ToolDevHelpers_Plugin_x64.zip
            ToolDevHelpers_Editor_x64.zip
