# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Create Plugin Build

on:
  workflow_dispatch:

  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    env:
      RELEASE_FOLDER: Community.PowerToys.Run.Plugin.JSLHelpers/bin/x64/Release/net8.0-windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: |
          dotnet build /p:Platform=x64 -c Release --no-restore

      - name: Upload build artifact
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v4.4.3
        with:
          # Artifact name
          name: tool-dev-helpers-plugin # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: |
            $env:RELEASE_FOLDER
            install_plugin.ps1
          # The desired behavior if no files are found using the provided path.
          retention-days: 3 # optional
          overwrite: true # optional, default is false

      - name: Create Release ZIP
        if: ${{ github.event_name == 'release' }}
        shell: pwsh
        run: |
          $compress = @{
            Path = "$env:RELEASE_FOLDER/*","install_plugin.ps1"
            CompressionLevel = "Fastest"
            DestinationPath = "ToolDevHelpers_x64.zip"
          }
          Compress-Archive @compress

      - name: Add release asset
        if: ${{ github.event_name == 'release' }}
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ToolDevHelpers_x64.zip
